/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import dao.UsuarioDao;
import datos.Conexion;
import datos.entidades.Usuario;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import utilidades.excepciones.BDException;

/**
 *
 * @author Zon50
 */
public class InicioDeSesion extends javax.swing.JFrame {

    /**
     * Creates new form InicioDeSesion
     */
    public InicioDeSesion() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ctUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ctPassword = new javax.swing.JPasswordField();
        btIS = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(36, 37, 39));

        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Inicio de sesión");

        ctUsuario.setFont(new java.awt.Font("NSimSun", 0, 32)); // NOI18N
        ctUsuario.setForeground(new java.awt.Color(0, 182, 223));
        ctUsuario.setText("Usuario");
        ctUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctUsuarioActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/iconos/UsuarioIDS.jpg"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/iconos/passwordIDC.jpg"))); // NOI18N

        ctPassword.setFont(new java.awt.Font("NSimSun", 0, 32)); // NOI18N
        ctPassword.setForeground(new java.awt.Color(0, 182, 223));
        ctPassword.setText("jPasswordField1");
        ctPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctPasswordActionPerformed(evt);
            }
        });

        btIS.setBackground(new java.awt.Color(51, 204, 255));
        btIS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/iconos/Botón IDS.png"))); // NOI18N
        btIS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btISMouseClicked(evt);
            }
        });
        btIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btISActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(ctUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ctPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(btIS, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ctUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ctPassword))
                .addGap(28, 28, 28)
                .addComponent(btIS, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ctUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctUsuarioActionPerformed

//    public void validarAcceso() {
//        Conexion conexion = new Conexion();
//        UsuarioDao usuarioDao = new UsuarioDao();
//
//        try {
//            conexion.iniciarConexion();
//            usuarioDao.setConexion(conexion.getConexion());
//
//            int resul = 0;
//
//            try {
//                String usuario = ctUsuario.getText();
//                String password = String.valueOf(ctPassword.getText());
//
//                String sql = "select * from usuario where nombre='" + usuario + "' and password ='" + password + "'";
//
//                Statement st = conexion.
//            
//
//            } catch (Exception e) {
//
//            }
//
//        } catch (BDException ex) {
//        } finally {
//            try {
//                conexion.cerrarConexion();
//            } catch (BDException ex) {
//
//            }
//        }
//    }

    private void btISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btISActionPerformed
//
//        Conexion conexion = new Conexion();
//        UsuarioDao usuarioDao = new UsuarioDao();
//
//        try {
//            conexion.iniciarConexion();
//            usuarioDao.setConexion(conexion.getConexion());
//
//        } catch (BDException ex) {
//        } finally {
//            try {
//                conexion.cerrarConexion();
//            } catch (BDException ex) {
//
//            }
//        }
        Conexion conexion = new Conexion();
        UsuarioDao usuarioDao = new UsuarioDao();

        try {
            conexion.iniciarConexion();
            usuarioDao.setConexion(conexion.getConexion());

            try {
                String usuario = ctUsuario.getText();

//                String sqlNombre = "select * from usuario where nombre='" + usuario + "' and password ='" + password + "'";
//                String sqlPass = "select * from usuario where nombre='" + usuario + "' and password ='" + password + "'";
//                usuarioDao.buscarNombre(usuario);
                Usuario user = usuarioDao.buscarUno(usuario);
                String password = String.valueOf(ctPassword.getText());
//                usuarioDao.buscarId(Integer.parseInt(password));
//                Statement st = conexion.createStatement();
//                ResultSet rs = st.executeQuery(sql);
                if (user.getPassword().equals(password)) {
                    VentanaPrincipal ventana = new VentanaPrincipal();
                    ventana.setVisible(true);
                    this.dispose();
                } else {

                    JOptionPane.showMessageDialog(null, "La contraseña o usuario ingresado no son validos.");
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error en el acceso, intente de nuevo" + e.getMessage());
            }

        } catch (BDException ex) {
        } finally {
            try {
                conexion.cerrarConexion();
            } catch (BDException ex) {

            }
        }

//        if (){
//            VentanaPrincipal ventana = new VentanaPrincipal();
//            ventana.setVisible(true);
//            this.dispose();
//        }
    }//GEN-LAST:event_btISActionPerformed

    private void ctPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctPasswordActionPerformed

    private void btISMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btISMouseClicked

//
    }//GEN-LAST:event_btISMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btIS;
    private javax.swing.JPasswordField ctPassword;
    private javax.swing.JTextField ctUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
